[package]
name = "offline-pymnt-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
libsecp256k1 = "0.7.2"
rand = "0.8.5"
sha3 = "0.10.8"
# tokio = { version = "1.46.1", features = ["full"] }
