use rand::rngs::OsRng;
use secp256k1::{PublicKey, Secp256k1, SecretKey};

// struct amount {
//     value: u64,
//     owner: u64,
// }

fn init() {
    // secp256k1 is used to generate (pk, sk) for each offline account
    let secp = Secp256k1::new();

    // random number generated by OS
    let mut rng = OsRng;

    // generate a (pk, sk) pair
    let (sk, pk) = secp.generate_keypair(&mut rng);

    println!("SK: {:?}", sk.display_secret());
    println!("PK: {:?}", pk);
}

fn main() {
    println!("Hello, world!");
}
